//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetshopApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ProductId { get; set; }
        public string Article { get; set; }
        public int ProductNameId { get; set; }
        public string Decription { get; set; }
        public string TypeProduct { get; set; }
        public decimal Price { get; set; }
        public int Discount { get; set; }
        public int ManufactorerId { get; set; }
        public int SupplierId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ActiveDiscount { get; set; }
        public Nullable<int> AllAmount { get; set; }
        public string PhotoName { get; set; }
        public byte[] PhotoProduct { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufactorer Manufactorer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual ProductName ProductName { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
